##################################
#                                #
#     Redis-Bridge-Inventory     #
#          v1.4 by DevSnx        #
#                                #
##################################

# Redis Server Connection
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""

# Saves (Inventory saved auto)
saves:
  hearts: true
  foodLevel: true
  exp: true
  expLevel: true
  potions: true

# Player Join Message (Use Color codes with &)
joinmessage:
  enable: true
  message: '&aYour inventory has been loaded successfully'