##################################
#                                #
#     Redis-Bridge-Inventory     #
#          v1.0 by DevSnx        #
#                                #
##################################

# Redis Server Connection
redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""

# Player Join Message
joinmessage:
  enable: true
  message: 'Inventory was Loaded from Redis-Inventory-Bridge'